# Dependencies
markdown:         kramdown

gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Bastian Rinsche
description:      'Newbie Android dev, </br> interesting &#38; fun stuff goes here.'
url:              http://blog.bastianrinsche.de

author:
  name:           'Bastian Rinsche'
  url:            https://twitter.com/memorion

paginate:         5
