# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bastian Rinsche
description:      'Newbie Android dev, </br> interesting &#38; fun stuff goes here.'
url:              https://memorion.github.io
baseurl:          /

author:
  name:           'Bastian Rinsche'
  url:            https://twitter.com/memorion

paginate:         5
